name: CI

on:
  workflow_call:
    inputs:
      build-target:
        required: true
        type: string

permissions:
  contents: read

jobs:
  build:
    name: ${{ inputs.build-target }} - ${{ matrix.os }}
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest]

    env:
      BUILD_TYPE: Release
      BUILD_DIR: build

    steps:
      - name: Setup Homebrew (Linux)
        if: runner.os == 'Linux'
        uses: Homebrew/actions/setup-homebrew@master

      - name: Show Homebrew info
        run: |
          which brew || echo "brew not in PATH"
          brew --version

      - name: Show compiler info
        run: |
          env
          command -v g++ clang++ gcc clang
          gcc --version
          g++ --version
          clang --version
          clang++ --version

      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup
        run: |
          make setup

      - name: Configure
        run: |
          make config

      - name: Build
        run: |
          make build

      - name: Test
        run: |
          make test
